name: Auto Sync LeetCode Solutions

on:
  schedule:
    - cron: "0 12 * * *" # every day at 6:30 AM IST
  workflow_dispatch:      # allow manual run

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install leetcode-api

    - name: Run Sync Script
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
      run: |
        python sync.py

    - name: Commit & Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add JAVA-EASY JAVA-MEDIUM JAVA-HARD README.md
        git commit -m "leetcode(java): sync solved problems" || echo "No changes"
        git push
